# Project information
site_name: Clinica Documentation
site_author: Clinica contributors
site_url: https://aramislab.paris.inria.fr/clinica/docs/public
site_description: >-
  Software platform for clinical neuroimaging studies

# Repository
repo_name: aramislab/clinica
repo_url: https://github.com/aramis-lab/clinica
#edit_uri: master/edit/doc

# Copyright
copyright: Copyright &copy; 2016-2021 Clinica contributors

# Google Analytics
google_analytics:
  - UA-106080699-1
  - auto

# Configuration
theme:
  name: material
  icon:
    repo: material/github
  language: en
  palette:
    primary: light blue
    accent: light blue

# Version panel
extra_javascript:
  - 'https://code.jquery.com/jquery-3.3.1.min.js'
      
# Customization
extra_css:
  - css/clinica.css

extra:
  feature:
    tabs: true
  social:
    - icon: material/github
      link: https://github.com/aramis-lab/
    - icon: material/twitter
      link: https://twitter.com/clinica_run
    - icon: material/earth
      link: http://www.aramislab.fr
  version:
    provider: mike

# Extensions
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.keys
  - pymdownx.superfences
  - toc:
      permalink: True

# Page tree
nav:
  - Home: index.md
  - Installation:
    - Installation: Installation.md
    - Third-party: Third-party.md
    # - Before your install: BeforeYouInstall
    # - ICM cluster installation: ICMClusterInstallation
  # - Quick start:
  - Clinica environment:
    - What is Clinica?: WhatIsClinica.md
    - Interacting with Clinica: InteractingWithClinica.md
    - BIDS: BIDS.md
    - CAPS:
      - Introduction: CAPS/Introduction.md
      - Specifications: CAPS/Specifications.md
    - Atlases: Atlases.md
  - Pipelines:
    - Anatomical MRI:
      - Linear processing: Pipelines/T1_Linear.md
      - Volume processing: Pipelines/T1_Volume.md
      - FreeSurfer processing: Pipelines/T1_FreeSurfer.md
      - FreeSurfer longitudinal processing: Pipelines/T1_FreeSurfer_Longitudinal.md
    - DWI:
      - Pre-processing: Pipelines/DWI_Preprocessing.md
      - DTI: Pipelines/DWI_DTI.md
      - Connectome: Pipelines/DWI_Connectome.md
    - PET:
      - Introduction: Pipelines/PET_Introduction.md
      - Linear processing: Pipelines/PET_Linear.md
      - Volume processing: Pipelines/PET_Volume.md
      - Surface processing: Pipelines/PET_Surface.md
      - Surface longitudinal processing: Pipelines/PET_Surface_Longitudinal.md
    - Statistics:
      - Surface-based mass-univariate analysis: Pipelines/Stats_Surface.md
      - Volume-based mass-univariate analysis: Pipelines/Stats_Volume.md
    - Machine Learning:
      - Prepare input data for spatially regularized SVM: Pipelines/MachineLearning_PrepareSVM.md
      - Classification based on machine learning: Pipelines/MachineLearning_Classification.md
  - Dataset converters:
    - ADNI to BIDS: Converters/ADNI2BIDS.md
    - AIBL to BIDS: Converters/AIBL2BIDS.md
    - HABS to BIDS: Converters/HABS2BIDS.md
    - NIFD to BIDS: Converters/NIFD2BIDS.md
    - OASIS to BIDS: Converters/OASIS2BIDS.md
    - OASIS-3 to BIDS: Converters/OASIS3TOBIDS.md
  - I/O tools:
    - create-subjects-visits: IO#create-subjects-visits-generate-the-list-all-subjects-and-visits-of-a-given-dataset
    - check-missing-modalities: IO#check-missing-modalities-check-missing-modalities-for-each-subject
    - check-missing-processing: IO#check-missing-processing-check-missing-processing-in-a-caps-directory
    - merge-tsv: IO#merge-tsv-gather-bids-and-caps-data-into-a-single-tsv-file
    - center-nifti: IO#center-nifti-center-the-nifti-files-of-a-bids-directory
  - Presentations & demos:
    - NOW 2019: ClinicaConferences#neuro-openscience-workshop-2019
    - OHBM 2018: ClinicaConferences#educational-course-on-pattern-recognition-for-clinical-neuroimaging-ohbm-2018
  # - Collaborate:
    # - Coding for Clinica: CodingForClinica
