# Project information
site_name: Clinica Documentation
site_author: Clinica contributors
site_url: https://aramislab.paris.inria.fr/clinica/docs/public/dev/
site_description: >-
  Software platform for clinical neuroimaging studies

# Repository
repo_name: aramislab/clinica
repo_url: https://github.com/aramis-lab/clinica
#edit_uri: master/edit/doc

# Copyright
copyright: Copyright &copy; 2016-2024 Clinica contributors

hooks:
  - my_hooks.py

# Configuration
theme:
  name: material
  icon:
    repo: material/github
    annotation: material/help-circle
  language: en
  palette:
    primary: light blue
    accent: light blue
  features:
    - content.tooltips
    - content.tabs.link
    - navigation.top

# Version panel
extra_javascript:
  - 'https://code.jquery.com/jquery-3.3.1.min.js'

# Customization
extra_css:
  - css/clinica.css

extra:
  feature:
    tabs: true

  social:
    - icon: material/github
      link: https://github.com/aramis-lab/
    - icon: material/twitter
      link: https://twitter.com/clinica_run
    - icon: material/earth
      link: http://www.aramislab.fr
  version:
    provider: mike

# Extensions
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.keys
  - pymdownx.superfences
  - pymdownx.critic
  - md_in_html
  - abbr
  - attr_list
  - md_in_html
  - pymdownx.snippets:
      base_path: docs
      auto_append:
        - snippets/abbreviations.md
        - snippets/support.md
  - toc:
      permalink: True
  - pymdownx.tabbed:
      alternate_style: True

not_in_nav: |
  /snippets/


# Page tree
nav:
  - Home: index.md
  - Setting-up for Clinica:
    - Installation: Software/Installation.md
    - Third-party software: Software/Third-party.md
    - Interacting with Clinica: Software/InteractingWithClinica.md
    - Contributing to Clinica : ../CONTRIBUTING.md
  - Clinica environment:
    - What is Clinica?: WhatIsClinica.md
    - BIDS: BIDS.md
    - CAPS:
      - Introduction: CAPS/Introduction.md
      - Specifications: CAPS/Specifications.md
    - Atlases: Atlases.md
  - Pipelines:
    - Anatomical MRI:
      - T1 Linear processing: Pipelines/T1_Linear.md
      - FLAIR Linear processing : Pipelines/FLAIR_Linear.md
      - Volume processing: Pipelines/T1_Volume.md
      - FreeSurfer processing: Pipelines/T1_FreeSurfer.md
      - FreeSurfer longitudinal processing: Pipelines/T1_FreeSurfer_Longitudinal.md
    - DWI:
      - Pre-processing: Pipelines/DWI_Preprocessing.md
      - DTI: Pipelines/DWI_DTI.md
      - Connectome: Pipelines/DWI_Connectome.md
    - PET:
      - Introduction: Pipelines/PET_Introduction.md
      - Linear processing: Pipelines/PET_Linear.md
      - Volume processing: Pipelines/PET_Volume.md
      - Surface processing: Pipelines/PET_Surface.md
      - Surface longitudinal processing: Pipelines/PET_Surface_Longitudinal.md
    - Statistics:
      - Surface-based mass-univariate analysis: Pipelines/Stats_Surface.md
      - Volume-based mass-univariate analysis: Pipelines/Stats_Volume.md
    - Machine Learning:
      - Prepare input data for spatially regularized SVM: Pipelines/MachineLearning_PrepareSVM.md
      - Classification based on machine learning: Pipelines/MachineLearning_Classification.md
  - Dataset converters:
    - ADNI to BIDS: Converters/ADNI2BIDS.md
    - AIBL to BIDS: Converters/AIBL2BIDS.md
    - GENFI to BIDS: Converters/GENFItoBIDS.md
    - HABS to BIDS: Converters/HABS2BIDS.md
    - IXI to BIDS: Converters/IXItoBIDS.md
    - NIFD to BIDS: Converters/NIFD2BIDS.md
    - OASIS to BIDS: Converters/OASIS2BIDS.md
    - OASIS-3 to BIDS: Converters/OASIS3TOBIDS.md
    - UK Biobank to BIDS: Converters/UKBtoBIDS.md
  - I/O tools:
    - create-subjects-visits: IO.md#create-subjects-visits-generate-the-list-all-subjects-and-visits-of-a-given-dataset
    - check-missing-modalities: IO.md#check-missing-modalities-check-missing-modalities-for-each-subject
    - check-missing-processing: IO.md#check-missing-processing-check-missing-processing-in-a-caps-directory
    - merge-tsv: IO.md#merge-tsv-gather-bids-and-caps-data-into-a-single-tsv-file
    - center-nifti: IO.md#center-nifti-center-the-nifti-files-of-a-bids-directory
    - describe: IO#describe-Describe-a-BIDS-or-CAPS-dataset
    - create-subjects-visits: IO#create-subjects-visits-generate-the-list-all-subjects-and-visits-of-a-given-dataset
    - check-missing-modalities: IO#check-missing-modalities-check-missing-modalities-for-each-subject
    - check-missing-processing: IO#check-missing-processing-check-missing-processing-in-a-caps-directory
    - merge-tsv: IO#merge-tsv-gather-bids-and-caps-data-into-a-single-tsv-file
    - center-nifti: IO#center-nifti-center-the-nifti-files-of-a-bids-directory
  - Presentations & demos:
    - NOW 2023: ClinicaConferences.md#neuro-openscience-workshop-2023
    - NOW 2019: ClinicaConferences.md#neuro-openscience-workshop-2019
    - OHBM 2018: ClinicaConferences.md#educational-course-on-pattern-recognition-for-clinical-neuroimaging-ohbm-2018
  - Glossary: glossary.md
  - What's new: CHANGELOG.md
