name: Freesurfer Anat Pipelines Tests

on:
  schedule:
    - cron: 0 20 * * 2 # every tuesday at 8pm

permissions:
  contents: read

env:
  POETRY_VERSION: '1.6.1'
  PYTHON_VERSION: '3.10'

jobs:
  test-pipelines-anat-freesurfer-MacOS:
    runs-on:
      - self-hosted
      - macOS
    timeout-minutes: 1440
    steps:
      - uses: actions/checkout@v4
      - uses: snok/install-poetry@v1
      - name: Run tests for anat pipelines using freesurfer
        run: |
          make env.conda
          source ~/miniconda3/etc/profile.d/conda.sh
          conda activate "${{ github.workspace }}"/env
          source "$(brew --prefix)/opt/modules/init/bash"
          module load clinica/freesurfer/6.0.0
          make install
          cd test
          poetry run pytest --verbose \
          --working_directory=/Volumes/data/working_dir_mac \
          --input_data_directory=/Volumes/data_ci \
          --basetemp=/Volumes/data/tmp \
          --junitxml=./test-reports/non_regression_anat_t1_freesurfer_mac.xml \
          --disable-warnings \
          ./nonregression/pipelines/anat/test_t1_freesurfer.py

  test-pipelines-anat-freesurfer-Linux:
    runs-on:
      - self-hosted
      - Linux
      - test-runner
    timeout-minutes: 1440
    steps:
      - uses: actions/checkout@v4
      - uses: snok/install-poetry@v1
        with:
          version: ${{ env.POETRY_VERSION }}
          virtualenvs-create: false
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: poetry
      - name: Run tests for anat pipelines using freesurfer
        run: |
          make env.conda
          source /builds/miniconda/etc/profile.d/conda.sh
          conda activate "${{ github.workspace }}"/env
          source /usr/local/Modules/init/profile.sh
          module load clinica/freesurfer/6.0.0
          make install
          cd test
          poetry run pytest --verbose \
          --working_directory=/mnt/data/ci/working_dir_linux \
          --input_data_directory=/mnt/data_ci \
          --basetemp=/mnt/data/ci/tmp \
          --junitxml=./test-reports/non_regression_anat_t1_freesurfer_linux.xml \
          --disable-warnings \
          ./nonregression/pipelines/anat/test_t1_freesurfer.py
